version: '3.8'

services:
  postgres-db:
    image: postgres:18
    container_name: ticket_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sql_class_2_db
    ports:
      - "5432:5432" # Mapping host port 5433 to container port 5432 to match your earlier JS config
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: